exclude: [RESOURCES.md, CONTRIBUTING.md, README.md]
url: "http://testthewebforward.com"
permalink: /blog/:year/:month/:day/:title.html
markdown: redcarpet
sponsors: [
  { "name": "Adobe",             "logo": "/assets/sponsors/adobe_red_black_logo.png" },
  { "name": "Facebook",          "logo": "/assets/sponsors/facebook_logo.jpeg" },
  { "name": "Google",            "logo": "/assets/sponsors/googlelogo.png" },
  { "name": "Internet Explorer", "logo": "/assets/sponsors/ie_logo.png" },
  { "name": "KDDI",              "logo": "/assets/sponsors/kddilogo.png" },
  { "name": "Microsoft",         "logo": "/assets/sponsors/mslogo.png" },
  { "name": "PhoneGap",          "logo": "/assets/sponsors/phonegap_logo.png" },
  { "name": "Telecom ParisTech", "logo": "/assets/sponsors/telecom_paristech_logo.png" },
  { "name": "W3C",               "logo": "/assets/sponsors/w3c_logo.png" },
  { "name": "Zenika",            "logo": "/assets/sponsors/zenika_logo.png" }
]
experts: [
  {
      "name": "Alan Stearns",
      "about": "Adobe, CSS Working Group",
      "pic": "/assets/experts/alan_stearns.jpg"
  },
  {
      "name": "Alex Danilo",
      "about": "Google, SVG Working Group",
      "pic": "/assets/experts/alex_danilo.jpg"
  },
  {
      "name": "Ally Ogilvie",
      "about": "Wizcorp",
      "pic": "/assets/experts/ally_ogilvie.jpg"
  },
  {
      "name": "Arno Gourdol",
      "about": "Adobe, CSS Working Group",
      "zho": "Adobe, CSS工作组",
      "pic": "/assets/experts/arno.jpg"
  },
  {
      "name": "Arron Eicholz",
      "about": "Microsoft, CSS Working Group",
      "pic": "/assets/experts/arron_eicholz.jpg"
  },
  {
      "name": "Brett Morgan",
      "about": "Google",
      "pic": "/assets/experts/brett_morgan.jpg"
  },
  {
      "name": "Brian Birtles",
      "about": "Mozilla, SVG Working Group",
      "pic": "/assets/experts/brian_birtles.jpg"
  },
  {
      "name": "Cameron McCormack",
      "about": "Mozilla, SVG Working Group co-chair",
      "pic": "/assets/experts/cameron_mccormack.jpg"
  },
  {
      "name": "Chris Lilley",
      "about": "W3C Standards Specialist",
      "pic": "/assets/experts/chris_lilley.jpg"
  },
  {
      "name": "Cyril Concolato",
      "about": "Telecom ParisTech, SVG Working Group",
      "pic": "/assets/experts/cyril_concolato.jpg"
  },
  {
      "name": "Daniel Davis",
      "about": "W3C, HTML5j Staff  ",
      "pic": "/assets/experts/DanielDavis.jpg"
  },
  {
      "name": "Daniel Glazman",
      "about": "Disruptive Innovations, CSS Working Group Co-Chair",
      "pic": "/assets/experts/daniel_glazman.jpg"
  },
  {
      "name": "Darryl Cain",
      "about": "Google",
      "pic": "/assets/experts/darryl_cain.jpg"
  },
  {
      "name": "Dave Methvin",
      "about": "President, jQuery Foundation",
      "pic": "/assets/experts/dave_methvin.jpg"
  },
  {
      "name": "David Rousset",
      "about": "Microsoft, HTML5 Developer Evangelist",
      "pic": "/assets/experts/david_rousset.jpg"
  },
  {
      "name": "Dirk Schulze",
      "about": "Adobe, SVG Working Group",
      "pic": "/assets/experts/dirk_schulze.jpg"
  },
  {
      "name": "Dmitry Baranovskiy",
      "about": "Adobe, SVG Working Group",
      "pic": "/assets/experts/dmitry_baranovskiy.jpg"
  },
  {
      "name": "Dominique Hazaël-Massieux",
      "about": "W3C Staff",
      "pic": "/assets/experts/Dom.jpg"
  },
  {
      "name": "Doug Schepers",
      "about": "W3C Standards Specialist",
      "pic": "/assets/experts/doug_schepers.png"
  },
  {
      "name": "Eiji Kitamura",
      "about": "Google Developer Advocate",
      "pic": "/assets/experts/eiji_kitamura.jpg"
  },
  {
      "name": "Emil A.Eklund",
      "about": "Google, Chrome/WebKit, DOM, Layout Expert",
      "pic": "/assets/experts/emil_eklund.png"
  },
  {
      "name": "Erik Dahlström",
      "about": "Opera, SVG Working Group co-chair",
      "pic": "/assets/experts/erik_dahlstrom.jpg"
  },
  {
      "name": "Ethan Malasky",
      "about": "Adobe，Web Platform资深开发经理",
      "pic": "/assets/experts/ethan.jpg"
  },
  {
      "name": "François Remy",
      "about": "Université Libre de Bruxelles",
      "pic": "/assets/experts/francois_remy.png"
  },
  {
      "name": "Glenn Adams",
      "about": "CoxCom, CSS Working Group",
      "pic": "/assets/experts/glenn_adams.jpg"
  },
  {
      "name": "Gérard Talbot",
      "about": "CSS 2.1 Test Suite Contributor",
      "pic": "/assets/experts/GerardTalbot-48x48.jpg"
  },
  {
      "name": "Hajime Shiozawa",
      "about": "CSS Test Suite Contributor",
      "pic": "/assets/experts/HajimeShiozawa.jpg"
  },
  {
      "name": "Henrik Kjellander",
      "about": "Google, Software Engineer in Test at Chrome/WebRTC",
      "pic": "/assets/experts/henrik_kjellander.jpg"
  },
  {
      "name": "Ido Green",
      "about": "Google, Developer Advocate, Author of Web Workers",
      "pic": "/assets/experts/ido_green.png"
  },
  {
      "name": "Jacob Goldstein",
      "about": "Adobe, WebKit Contributor",
      "pic": "/assets/experts/jacob_goldstein.png"
  },
  {
      "name": "Jacob Rossi",
      "about": "Microsoft, Pointer Events Working Group",
      "pic": "/assets/experts/jacob_rossi.jpg"
  },
  {
      "name": "James Graham",
      "about": "Opera, testharness.js Author",
      "pic": "/assets/experts/james_graham.jpeg"
  },
  {
      "name": "Jared Wyles",
      "about": "Adobe",
      "pic": "/assets/experts/jared_wyles.jpg"
  },
  {
      "name": "Jeremie Patonnier",
      "about": "Clever Age, SVG and CSS expert",
      "pic": "/assets/experts/jeremie_patonnier.jpg"
  },
  {
      "name": "Jet Villegas",
      "about": "Mozilla, CSS Working Group",
      "pic": "/assets/experts/jet_villegas.jpg"
  },
  {
      "name": "John Allsopp",
      "about": "Web Directions founder, Web luminary",
      "pic": "/assets/experts/john_allsopp.png"
  },
  {
      "name": "John Daggett",
      "about": "Mozilla, CSS Working Group",
      "pic": "/assets/experts/johndaggett.jpg"
  },
  {
      "name": "John Jansen",
      "about": "Microsoft, CSS Working Group",
      "pic": "/assets/experts/john_jansen.jpg"
  },
  {
      "name": "Julien Chaffraix",
      "about": "Google, CSS 2.1 Tables & CSS3 Grid Layout Expert",
      "pic": "/assets/experts/julien_chaffraix.png"
  },
  {
      "name": "Kazuaki Takemura",
      "about": "Game and Web Developer, CSS Working Group",
      "pic": "/assets/experts/takemura.jpg"
  },
  {
      "name": "Kensaku Komatsu",
      "about": "NTT Communications, HTML5 advocate in Japanese community",
      "pic": "/assets/experts/kensaku_komatsu.jpg"
  },
  {
      "name": "Koji Ishii",
      "about": "Rakuten",
      "pic": "/assets/experts/koji_ishii.jpg"
  },
  {
      "name": "Kris Krueger",
      "about": "Microsoft, HTML Working Group",
      "pic": "/assets/experts/Kris_Krueger.jpg"
  },
  {
      "name": "L. David Baron",
      "about": "Mozilla, CSS Working Group",
      "pic": "/assets/experts/l_david_baron.jpg"
  },
  {
      "name": "Leif Arne Storset",
      "about": "Opera, CSS Working Group",
      "pic": "/assets/experts/leifarnestorset.jpg"
  },
  {
      "name": "Levi Weintraub",
      "about": "Google, Chrome/WebKit, Rendering, Line Layout, Bidi Expert",
      "pic": "/assets/experts/levi_weintraub.jpg"
  },
  {
      "name": "Masahito Kawamori",
      "about": "Software Quality Assurance Manager, Keio University/W3C",
      "pic": "/assets/experts/testtwf_default.gif"
  },
  {
      "name": "Masataka Yakura",
      "about": "HTML5J",
      "pic": "/assets/experts/masataka_yakura.jpg"
  },
  {
      "name": "Michael Brooks",
      "about": "Adobe, PhoneGap and Apache Cordova Developer",
      "pic": "/assets/experts/michael_brooks.png"
  },
  {
      "name": "Michael[tm] Smith",
      "about": "W3C HTML Activity Lead",
      "pic": "/assets/experts/michael_smith.jpg"
  },
  {
      "name": "Mike West",
      "about": "Google, Developer Advocate, Contact Security Policy expert",
      "pic": "/assets/experts/mike_west.jpg"
  },
  {
      "name": "Odin Hørthe Omdal",
      "about": "Opera, IndexedDB Expert",
      "pic": "/assets/experts/odin-horthe-omdal-pressebilete.jpg"
  },
  {
      "name": "Oli Studholme",
      "about": "iA, HTML5 Doctor",
      "pic": "/assets/experts/oli_studholme.jpg"
  },
  {
      "name": "Patrik Höglund",
      "about": "Google, Software Engineer in Test at Chrome/WebRTC",
      "pic": "/assets/experts/patrik_hoglund.jpg"
  },
  {
      "name": "Peter Linss",
      "about": "HP, CSS Working Group Co-Chair",
      "pic": "/assets/experts/peter-linns.jpg"
  },
  {
      "name": "Philip Rogers",
      "about": "Google, WebKit Contributor",
      "pic": "/assets/experts/philip_rogers.jpg"
  },
  {
      "name": "Philippe Le Hégaret",
      "about": "W3C Interaction Domain Leader",
      "pic": "/assets/experts/philippe.jpg"
  },
  {
      "name": "Rebecca Hauck",
      "about": "Adobe, CSS Working Group",
      "pic": "/assets/experts/rebecca_hauck.png"
  },
  {
      "name": "Rik Cabanier",
      "about": "Adobe, SVG Working Group and Canvas editor",
      "pic": "/assets/experts/rik_cabanier.jpg"
  },
  {
      "name": "Robin Berjon",
      "about": "W3C, DAP Working Group Co-Chair",
      "pic": "/assets/experts/robin_berjon.jpg"
  },
  {
      "name": "Ryosuke Niwa",
      "about": "Google, WebKit Contributor",
      "pic": "/assets/experts/ryosuke_niwa.jpg"
  },
  {
      "name": "Shigeo Okamoto",
      "about": "Deputy Director, Standardization Division, Ministry of Internal Affairs and Communications",
      "pic": "/assets/experts/okamoto.jpg"
  },
  {
      "name": "Shinyu Murakami",
      "about": "Antenna House, Developer",
      "pic": "/assets/experts/shinyu_murakami.jpg"
  },
  {
      "name": "Silvia Pfeiffer",
      "about": "W3C HTML5 co-editor, Google",
      "pic": "/assets/experts/silvia_pfeiffer.jpg"
  },
  {
      "name": "Simon Pieters",
      "about": "Opera, HTML Expert, Quirks Mode Spec Editor",
      "pic": "/assets/experts/simon_pieters.jpg"
  },
  {
      "name": "Simon Sapin",
      "about": "Mozilla, CSS WG",
      "pic": "/assets/experts/simon_sapin.png"
  },
  {
      "name": "Steve Zilles",
      "about": "Adobe, CSS Working Group",
      "pic": "/assets/experts/steve_zilles.jpg"
  },
  {
      "name": "Sylvain Galineau",
      "about": "Microsoft, CSS Working Group",
      "pic": "/assets/experts/sylvain_galineau.png"
  },
  {
      "name": "Tab Atkins Jr.",
      "about": "Web Standards Hacker, Google",
      "pic": "/assets/experts/tabatkinsjr.jpg"
  },
  {
      "name": "Tim Ansell",
      "about": "Google",
      "pic": "/assets/experts/tim_ansell.jpg"
  },
  {
      "name": "Tobie Langel",
      "about": "Facebook, W3C AC Rep",
      "pic": "/assets/experts/tobie_langel.jpg"
  },
  {
      "name": "Tomomi Imura",
      "about": "Nokia Developer Evangelist, Emerging Platforms",
      "pic": "/assets/experts/tomomi_imura.jpg"
  },
  {
      "name": "Vincent Hardy",
      "about": "Adobe, SVG Working Group",
      "pic": "/assets/experts/vincent_hardy.png"
  },
  {
      "name": "fantasai",
      "about": "Mozilla, CSS Working Group",
      "pic": "/assets/experts/fantasai.jpg"
  },
  {
      "name": "丁建宁",
      "about": "Google，Chrome team成员，WebKit Committer",
      "pic": "/assets/experts/dingjianning.jpg"
  },
  {
      "name": "于涛",
      "about": "腾讯，Web前端AlloyTeam主管，WebQQ高级工程师",
      "pic": "/assets/experts/yutao.jpg"
  },
  {
      "name": "傅静",
      "about": "Intel中国，资深软件工程师",
      "pic": "/assets/experts/fujing.jpg"
  },
  {
      "name": "占红涛",
      "about": "傲游，Maxthon前端组，前端工程师",
      "pic": "/assets/experts/zhanhongtao.jpg"
  },
  {
      "name": "吕康豪",
      "about": "欧朋，欧朋Web标准团队，W3C HTML5中文兴趣小组固定班底",
      "pic": "/assets/experts/kenny.jpg"
  },
  {
      "name": "孙铁",
      "about": "百度，手机浏览器内核QA",
      "pic": "/assets/experts/suntie.jpg"
  },
  {
      "name": "张云龙",
      "about": "Mozilla中国，火狐中文相关WEB项目架构师",
      "pic": "/assets/experts/zhangyunlong.jpg"
  },
  {
      "name": "张坚",
      "about": "Adobe中国，开发组长",
      "pic": "/assets/experts/zhangjian.jpg"
  },
  {
      "name": "张志强",
      "about": "Intel中国，资深软件工程师，Tizen WebAPI 专家",
      "pic": "/assets/experts/zhangzhiqiang.jpg"
  },
  {
      "name": "张金龙",
      "about": "欧朋，欧朋Web标准团队，网站兼容性优化工程师",
      "pic": "/assets/experts/zhangjinlong.jpg"
  },
  {
      "name": "沈达泱",
      "about": "百度，手机浏览器内核QA工程师",
      "pic": "/assets/experts/shendayang.jpg"
  },
  {
      "name": "王健",
      "about": "UC优视科技，浏览器研发部高级研发经理",
      "pic": "/assets/experts/wangjian.jpg"
  },
  {
      "name": "胡雷",
      "about": "百度，移动云测试部高级项目经理",
      "pic": "/assets/experts/hulei.jpg"
  },
  {
      "name": "董龙飞",
      "about": "Adobe中国，技术推广师",
      "pic": "/assets/experts/donglongfei.jpg"
  },
  {
      "name": "赵莉萍",
      "about": "Adobe中国，资深QA工程师",
      "pic": "/assets/experts/zhaoliping.jpg"
  },
  {
      "name": "郭鹏程",
      "about": "百度，资深软件工程师",
      "pic": "/assets/experts/guopengcheng.jpg"
  },
  {
      "name": "靖轲",
      "about": "华为，天天浏览器内核专家",
      "pic": "/assets/experts/jingke.jpg"
  },
  {
      "name": "高寒蕊",
      "about": "360，前Google Chrome 开发技术推广工程师，非典型HTML5开发人员",
      "pic": "/assets/experts/gaohanrui.jpg"
  },
  {
      "name": "魏凡哲(花名：陶清)",
      "about": "淘宝，淘宝UED前端工程师",
      "pic": "/assets/experts/taoqing.jpg"
  }
]